### ISSUE TITLE
The 8" screen template is upside down

### ISSUE THREAD

**Issue by jaydeetay** [pimoroni/picade#2]
https://github.com/pimoroni/picade/blob/master/picade-docs/picade-artwork-templates-a4.pdf

I learned this the hard way after spending $100 on printing :(

**Comment by guru** [comment]
Oh no! Do you still have the upside down prints?
Drop an email to me paul  (at that there) pimoroni (dotted to the) com and I think I might have a solution for this!

**Comment by jaydeetay** [comment]
Done! The picades look great anyway...we just have our base shooting down instead of up!
